### ISSUE TITLE
rename kiev to kyiv

### ISSUE THREAD

**Issue by PeerRich** [kevinroberts/city-timezones#27]
https://www.cbc.ca/news/world/cbc-pronunciation-kyiv-ukraine-crisis-explainer-1.6371766

**Comment by adrienv1520** [comment]
Hey @PeerRich we've just published a package that could fix your problem while bringing more features: https://github.com/elysiumphase/node-location-timezone. We've cleaned all the data and Kyiv is referenced there as a valid city name.

**Comment by kevinroberts** [comment]
I will publish an updated version shortly. Thanks for the contribution.
