### ISSUE TITLE
Is there an option where i put city, country and it tells the timezone?

### ISSUE THREAD

**Issue by techsin** [kevinroberts/city-timezones#5]
ny, usa 

new york, us

NY, us

new york, united states of america

**Comment by kevinroberts** [comment]
This library so far is meant to just process searches via a known city or city and state combination. If you search just New York you can retrieve its associated properties. I don't have a method for city and country but you can add one if you would like to contribute.

**Comment by techsin** [comment]
only reliable way i found was to use google maps api, using this reduced the api calls i've to make as i didn't have to make timezone api call

**Comment by Rotimi-Best** [comment]
@techsin I created a [module](https://www.npmjs.com/package/city-country-timezone) for such use case. You can check it out and make a PR if needed. It actually depends fully on this library so thanks to @kevinroberts .
