### ISSUE TITLE
Data json it's outdated

### ISSUE THREAD

**Issue by mahenrique94** [kevinroberts/city-timezones#7]
I tried to use this one, but, some cities has no data.

**Comment by Rotimi-Best** [comment]
which cities did you try?

**Comment by doombringerfunk** [comment]
I just found Copenhagen is missing.

**Comment by Rotimi-Best** [comment]
@kevinroberts Just fixed it, you can check it again c8369e95edeceb35a70c5162cc3ff22c7726cd71

**Comment by kevinroberts** [comment]
See other open issue for missing cities from json source. Will need help in adding more though.
